apiVersion: v1
kind: ConfigMap
metadata:
  name: dhs-gitea-cm
data:
  GITEA__database__DB_TYPE: "mysql"
  GITEA__database__HOST: "dhs-gitea-mysql-svc.app2.svc.cluster.local:3307" # Adding new apps remember to change this to different svc url dhs-gitea-mysql-svc.[YOUR_NAMESPACE].svc.cluster.local:[YOUR_SQL_PORT]
  GITEA__database__NAME: "dhs-gitea"
  GITEA__database__USER: "dhs-gitea"
  GITEA__database__PASSWD: "dhs-gitea-secret"
  MYSQL_ROOT_PASSWORD: "dhs-gitea-rootsecret"
  MYSQL_DATABASE: "dhs-gitea"
  MYSQL_USER: "dhs-gitea"
  MYSQL_PASSWORD: "dhs-gitea-secret"
  TENANT: "main"
  GITEA_PORT: "4000" # Adding new apps remember to change this to different port - make same as service.yaml
  GITEA_SSH_PORT: "2223" # Adding new apps remember to change this to different port  - make same as service.yaml