version: "3"

networks:
  dhs-gitea:
    external: false

services:
  server:
    container_name: dhs-gitea-server
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # See other available environment at https://github.com/go-gitea/gitea/blob/main/contrib/environment-to-ini/README
    restart: always
    networks:
      - dhs-gitea
    volumes:
      # The configuration file will be saved at ./gitea-data/gitea/conf/app.ini
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"