version: "3.8"

networks:
  dhs-gitea:
    external: false

services:
  server:
    image: gradient0/dhs-gitea:${IMAGE_TAG_DHS_GITEA:-latest}
    container_name: dhs-gitea-${TENANT:-default}-server
    env_file:
      - .env
    restart: always
    networks:
      - dhs-gitea
    volumes:
      #- gitea-data:/var/lib/gitea
      - /home/git/sandbox/data:/data
      - /home/git/.ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:${GITEA_PORT:-3000}:3000"
      - "0.0.0.0:${GITEA_SSH_PORT:-222}:22"
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    container_name: dhs-gitea-db-${TENANT:-default}-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${MYSQL_EXPOSE_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-init:/docker-entrypoint-initdb.d
    networks:
      - dhs-gitea

volumes:
  gitea-data:
    driver: local
  db-data:
    driver: local
  db-init:
    driver: local
